services:
  postgres:
    container_name: keycloak_postgres
    #image: postgres:latest
    image: postgres:17.3-alpine
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: kc
      #TZ: Europe/Rome
    networks:
      - keycloak_network
    volumes:
      - psql_data:/var/lib/postgresql/data/
      #- ./shared:/opt/shared
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "keycloak_db", "-U", "keycloak" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    restart: unless-stopped
      
  keycloak:
    container_name: keycloak_server
    #image: quay.io/keycloak/keycloak:latest
    image: quay.io/keycloak/keycloak:26.1.2
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: temp-admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: temp-admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak_db
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: kc
      KC_DB_POOL_INITIAL_SIZE: 5
      KC_DB_POOL_MIN_SIZE: 5
      KC_DB_POOL_MAX_SIZE: 15
      DEBUG: true
      DEBUG_PORT: '*:8787'
      #TZ: Europe/Rome
    ports:
      - 8080:8080 # http
      - 8443:8443 # https
      - 9000:9000 # management interface
      - 8787:8787 # debug port
    networks:
      - keycloak_network
    volumes:
      - ./bin/docker-entrypoint.sh:/home/keycloak/docker-entrypoint.sh
      - ./custom:/home/keycloak/customizations
      - ./shared:/opt/shared
    entrypoint: ["/home/keycloak/docker-entrypoint.sh"]
    restart: unless-stopped

networks:
  keycloak_network:
    driver: bridge
    
volumes:
    psql_data:
        driver: local